### ISSUE TITLE
Failed to set upload rate

### ISSUE THREAD

**Issue by codedesperate** [uraid/rtorrent_throttle#1]
Hi there, 
I just found your script and it looks great! I am having some issues though. When I run it I get:

```
[*] Checking RPC server connection
[+] RPC server connection is OK
[*] New max upload rate is already set: Unlimited
[+] Previous max upload rate: 1048576KB/s
[*] Setting max upload rate: 1024KB/s
[-] Failed setting max upload rate. Rate didn't change
```

These are the variables I've used:

```
RTORRENT_USER   = "CENSORED"
RTORRENT_PASS   = "CENSORED"
RTORRENT_URL    = "localhost"
RPC_PATH        = "plugins/rpc/rpc.php"
RTORRENT_RPC    = f"http://{RTORRENT_USER}:{RTORRENT_PASS}@{RTORRENT_URL}/{RPC_PATH}"
```

I am running rutorrent v4.1.8
Is the script compatible with this rutorrent version?

**Comment by uraid** [comment]
The RPC shouldn't have changed in the latest rutorrent versions. Can you please send the log with `DEBUG=True` inside the script?

**Comment by codedesperate** [comment]
The output I send in my first message is with Debug set to true already. If Debug is set to false, then the script won't output anything at all. As far as I can see from the code, there isn't any additional log file than the output from the script, right?

**Comment by uraid** [comment]
Yeah, no additional log exists.
It seems from what you sent that the communication with the RPC succeeds, but only the speed limit is not changed.
I also don't see any changes in the RPC: https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-throttle-global-up-max-rate-set-kb
Can you try setting the max upload speed manually in rutorrent and running the script again?
Also, what Python version are you using and is your machine x32 or x64?

**Comment by codedesperate** [comment]
If I open rutorrent in the GUI and manually sets upload limit to 2048, then rutorrent show that there is a limit. 
Then I run the following:
```
root@zeroz:/opt/rtorrent_throttle# ./rtorrent_throttle.py -D -1 -U 1024
[*] Checking RPC server connection
[+] RPC server connection is OK
[*] New max upload rate is already set: Unlimited
[+] Previous max upload rate: 2048KB/s
[*] Setting max upload rate: 1024KB/s
[+] Sucessfully set max upload rate
```

And I can see that the script changes the upload back to unlimited, when it was supposed to set it at 1024. 

If I run the command again I get this:
```
root@zeroz:/opt/rtorrent_throttle# ./rtorrent_throttle.py -D -1 -U 1024
[*] Checking RPC server connection
[+] RPC server connection is OK
[*] New max upload rate is already set: Unlimited
[+] Previous max upload rate: 1048576KB/s
[*] Setting max upload rate: 1024KB/s
[-] Failed setting max upload rate. Rate didn't change
```

```
root@zeroz:/opt/rtorrent_throttle# /usr/bin/python3 --version
Python 3.10.12
```

I am running Ubuntu 22.04.3 x64

**Comment by uraid** [comment]
Thanks for the details!
Apparently, there was indeed a change in the API.
A fix will arrive shortly.

**Comment by codedesperate** [comment]
Was just about to write! 

I noticed that if I set: ./rtorrent_throttle.py -D -1 -U 2, than actually sets a limit of 2048 in rutorrent. So setting it to 1024, gives it the maximum value, therefore not setting a limit. 

Using -1 gives me an error though:
```
root@zeroz:/opt/rtorrent_throttle# ./rtorrent_throttle.py -D -1 -U -1
[*] Checking RPC server connection
[+] RPC server connection is OK
[*] New max upload rate is already set: Unlimited
[+] Previous max upload rate: 1048576KB/s
[*] Setting max upload rate: Unlimited
Traceback (most recent call last):
  File "/opt/rtorrent_throttle/./rtorrent_throttle.py", line 132, in <module>
    main()
  File "/opt/rtorrent_throttle/./rtorrent_throttle.py", line 128, in main
    if not throttle_obj.throttle_upload(args.maxupload):
  File "/opt/rtorrent_throttle/./rtorrent_throttle.py", line 103, in throttle_upload
    if not self.set_max_upload_rate(maxupload):
  File "/opt/rtorrent_throttle/./rtorrent_throttle.py", line 55, in set_max_upload_rate
    return self.rpc_server.throttle.global_up.max_rate.set_kb("", rate) == 0
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -503: 'Throttle rate must be between 0 and 2^30.'>
root@zeroz:/opt/rtorrent_throttle#
```

**Comment by uraid** [comment]
This is due to a bug in API version 9 that makes `set_kb()` API call set bytes instead of kilobytes.
But, in API version 10 it was fixed so it tries to set it to be `1024` MBs instead (my convertion).
The fix will check the API version and act accordingly

**Comment by uraid** [comment]
Thank you for reporting it @codedesperate !
Let me know how that works out for you.

**Comment by codedesperate** [comment]
@uraid works perfect! Thank you! Now the family can finally stop complaining because I run out of upload speed on my home connection with rutorrent hogging it all! :D
