### ISSUE TITLE
Limit not removed

### ISSUE THREAD

**Issue by codedesperate** [uraid/rtorrent_throttle#3]
Hi, I am not sure if this is even a bug in this script, or if it is Tautulli's or the Plex players fault. 

But I've found, that when watching a remote stream on an android client, and if the stream is stopped at the very end (So Plex would consider the media "seen") Then a "stop" notification isn't recorded by Tautulli, and therefore the script is not triggered. 

If I start the remote stream on the Android device and close the stream at any point except at the very end, then the notification works and the script executes. 

So when a remote user watches something, and then when the credits starts the user closes the stream, no stop event is sent to Tautulli, and the limit is left "on" in rtorrent. 

If this is indeed a limitation of the player / tautulli, is there then any way around this? If tautulli had an option "Trigger every 5min" then I would enable that, in order to make sure a limit is removed if the stopped stream isn't correctly recorded. 

Or maybe a second script is needed? Something that checks every 5min if no remote stream is active, and executes this script accordingly?

**Comment by uraid** [comment]
This is definitely something in the way Tautulli notification are getting triggered.
After tinkering a bit, I see there is also a 'Watched' notification:
`Trigger a notification when a stream reaches the specified watched or listened threshold.`

Can you try enabling this one as well and checking again?
If this fixes it I'll add it to the README.

**Comment by codedesperate** [comment]
Hi @uraid,
I've done the following.

1. Enabled `Watched` as a trigger. 
2. Added a fourth condition: `Remaining Duration (sec) is less than 600`
3. Set condition logic to `{1} and {2} or {3} or {4}`
4. Set `-D -1 -U -1` as argument under `Watched` 

This works regardless of the media being watched already having watched status or not ( a good thing )

However, it doesn't really solve the problem. Because now when the watched media reaches 90% and the script is triggered, rtorrent will hog all the upload, and the media will start to buffer at the very end. 

Ideally, I would use `Credits Marker` instead of `Watched`. But I cannot get this to work. I've tried the same config as above, but instead having a trigger for `Credits Marker`, and adjusting the arguments section. But this didn't work. 
With this setup, stuttering would start at the end of a movie which can be frustrating too.

**Comment by uraid** [comment]
Try removing the fourth conidition, then doing like so:
`Settings > Notifications & Newsletters > Allow Playback Stop Notifications Exceeding Watched Percent (show advanced).`

This should use the Plex built-in calculation.
I hope it would help.

**Comment by codedesperate** [comment]
@uraid that was it! :D 
That option should definitely be added to the documentation! I don't need to use the watch trigger at all now, enabling that option completely fixed it!
